Razor/Models/Address.cs
namespace Razor.Models
{
    public class Address
    {
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    }
}

Razor/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace Razor.Models
{
        public class Client
        {
            // [Required]
            public string FirstName { get; set; }
            // [Required]
            public string LastName { get; set; }
            // [Required]
            public string CompanyName { get; set; }
            // [Required]
            // [EmailAddress]
            // [Remote("VerifyEmail", "Client")]
            public string Email { get; set; }
            // [Required]
            public string Phone { get; set; }
            // [Required]
            public DateTime? ContactDate { get; set; }
            // [Required]
            public string ClientType { get; set; }
            public string NearestLocation { get; set; }
            // [Required]
            // [MaxLength(25)]
            public string Notes { get; set; }
            public List<EmailPromo> EmailPromos { get; set; }
            public Address BillingAddress { get; set; }
            public Address MailingAddress { get; set; }
        }
}

Razor/Models/EmailPromo.cs
namespace Razor.Models
{
    public class EmailPromo
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool IsSubscribed { get; set; }
    }
}

Razor/Models/ErrorViewModel.cs
using System;

namespace Razor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Razor/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Razor.Models
{
        public class Order
        {
            [Required(ErrorMessage = "We need to know who they are!")]
            public string ClientId { get; set; }
            [Required(ErrorMessage = "The Company Name is a must!")]
            public string CompanyName { get; set; }
            [Required]
            public string OrderDate { get; set; }
            [Required]
            public string Stage { get; set; }
            public List<OrderProductVM> Products { get; set; }
            [Required]
            public string ShippingAddress { get; set; }
            [Required]
            public string OrderInstructions { get; set; }
            [Required]
            [MaxLength(25)]
            public string Notes { get; set; }
        }

        public class OrderProductVM
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public int? Quantity { get; set; }
        }
}

Razor/Models/OrderSummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor.Models
{
    public class OrderSummary
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime LastUpdated { get; set; }
    }
}

Razor/Models/SelectListItem.cs
namespace Razor.Models
{
    public class SelectListItem
    {
        public string Text { get; set; }
    }
}

Razor/Controllers/ClientController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Razor.Models;

namespace Razor.Controllers
{
    public class ClientController : Controller
    {
        // GET
        public IActionResult NewClient()
        {
            var newClient = new Client();
            newClient.EmailPromos = new List<EmailPromo>()
            {
                new EmailPromo() { Id = 1, Title = "Weekly Deal", IsSubscribed = false },
                new EmailPromo() { Id = 2, Title = "Holiday Promos", IsSubscribed = false },
                new EmailPromo() { Id = 3, Title = "Company Newsletter", IsSubscribed = false },
                new EmailPromo() { Id = 4, Title = "New Products", IsSubscribed = false }
            };
            
            return View(newClient);
        }
        
        [HttpPost]
        public IActionResult NewClient(Client newClient)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");    
            }
            else
            {
                return View(newClient);
            }
        }

        public IActionResult VerifyEmail(string email)
        {
            var emailList = new List<string>()
            {
                "test@example.com",
                "hello@example.com",
                "world@example.com"
            };

            if (emailList.Contains(email))
            {
                return Json("Email is already taken");
            }

            return Json(true);
        }
    }
}

Razor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Razor.Models;

namespace Razor.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var OrderSummarys = new List<OrderSummary>()
            {
                new OrderSummary() { Name = "Donec id elit non", LastUpdated = DateTime.Now.AddDays(-2), Description = "Maecenas sed diam eget risus varius blandit. Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit. Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit." },
                new OrderSummary() { Name = "Maecenas sed diam eget risus", LastUpdated = DateTime.Now.AddDays(-3), Description = "Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit. Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit." },
                new OrderSummary() { Name = "Maecenas sed diam eget risus", LastUpdated = DateTime.Now.AddDays(-8), Description = "Maecenas sed diam eget risus varius blandit. Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit." },
                new OrderSummary() { Name = "Donec id elit non", LastUpdated = DateTime.Now.AddDays(-2), Description = "Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit. Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit." },
                new OrderSummary() { Name = "Maecenas sed diam eget risus", LastUpdated = DateTime.Now.AddDays(-5), Description = "Maecenas sed diam eget risus varius blandit. Maecenas sed diam eget risus varius blandit. Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit." },
                new OrderSummary() { Name = "Donec id elit non", LastUpdated = DateTime.Now.AddDays(-15), Description = "Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit." }
            };

            ViewBag.OrderSummarys = OrderSummarys;
            
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Vote(int id)
        {
            return ViewComponent("SurveyWidget", new {productId = id});
        }
    }
}

Razor/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Razor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult NewOrder()
        {
            var newOrder = new Order();
            newOrder.Products = new List<OrderProductVM>()
            {
                new OrderProductVM() { Id = 1, Name = "Hoodie" },
                new OrderProductVM() { Id = 2, Name = "T-Shirt" },
                new OrderProductVM() { Id = 3, Name = "Banner" },
                new OrderProductVM() { Id = 4, Name = "Table Cloth" },
                new OrderProductVM() { Id = 5, Name = "Streamers" }
            };
            return View(newOrder);
        }

        [HttpPost]
        public IActionResult NewOrder(Order newOrder)
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

Razor/Views/Client/NewClient.cshtml
@using SelectListItem = Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
@model Razor.Models.Client
@inject Razor.Services.IFormDataService FormDatHelper 

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Add a New Client <br />
                <small>We're always happy to gain new customers.</small>
            </h1>
        </div>
    </div>
   
    @using (Html.BeginForm("NewClient", "Client", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md-6">
                @Html.ValidationSummary(false)
                <div class="form-group">
                    @Html.LabelFor(u => u.FirstName, "First Name")
                    @Html.TextBoxFor(u => u.FirstName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.LastName, "Last Name")
                    @Html.TextBoxFor(u => u.LastName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.CompanyName, "Company Name")
                    @Html.TextBoxFor(u => u.CompanyName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.Phone, "Phone")
                    @Html.TextBoxFor(u => u.Phone, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.Email, "Email")
                    @Html.TextBoxFor(u => u.Email, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.ContactDate, "Contact Date")
                    @Html.TextBoxFor(u => u.ContactDate, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.ClientType, "Client Type")
                    @Html.DropDownListFor(u => u.ClientType, FormDatHelper.GetClientTypes(), new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(u => u.NearestLocation, "Client Type")
                    @Html.DropDownListFor(u => u.ClientType, FormDatHelper.GetLocations(), new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-4">
                @await Component.InvokeAsync("InventoryWIdget", new { threshold = 20 })
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 form-group">
                @Html.LabelFor(u => u.Notes, "Notes")
                @Html.TextBoxFor(u => u.Notes, new { @class= "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 form-group">
                <label>Subscribe to:</label>
                <div>
                    @for (var i = 0; i < Model.EmailPromos.Count; i++)
                    {
                        @Html.CheckBoxFor(e => e.EmailPromos[i].IsSubscribed)
                        <span>@Model.EmailPromos[i].Title</span>
                        @Html.HiddenFor(e => e.EmailPromos[i].Id)
                        @Html.HiddenFor(e => e.EmailPromos[i].Title)
                    }
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h3>Billing Address</h3>
                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.BillingAddress.Street)
                        @Html.TextBoxFor(x => x.BillingAddress.Street, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.BillingAddress.City)
                        @Html.TextBoxFor(x => x.BillingAddress.City, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.BillingAddress.State)
                        @Html.TextBoxFor(x => x.BillingAddress.State, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.BillingAddress.Zip)
                        @Html.TextBoxFor(x => x.BillingAddress.Zip, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h3>Mailing Address</h3>
                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.MailingAddress.Street)
                        @Html.TextBoxFor(x => x.MailingAddress.Street, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.MailingAddress.City)
                        @Html.TextBoxFor(x => x.MailingAddress.City, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.MailingAddress.State)
                        @Html.TextBoxFor(x => x.MailingAddress.State, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(x => x.MailingAddress.Zip)
                        @Html.TextBoxFor(x => x.MailingAddress.Zip, new { @class = "form-control" })
                    </div>
                </div>
                <input type="submit" class="pull-right btn btn-primary" />
            </div>
        </div>
    }
</div>
@section Footer
{
    <p>Make sure to send new clients a welcome package.</p>
}

Razor/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Razor/Views/Home/Index.cshtml
	<!-- Begin View Wrapper -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Welcome to the Ordering Application! <br />
                        <small>Here you can manage inventory and orders for our customers.</small>
                    </h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Pending Orders</h3>
                        </div>
                        <div class="panel-body">
                            <div class="list-group">
                                @{
                                    foreach (var order in ViewBag.OrderSummarys)
                                    {
                                        <a href="#" class="list-group-item">
                                            <h4 class="list-group-item-heading">@order.Name
                                                <span class="pull-right">Last Updated: @order.LastUpdated</span></h4>
                                            <p class="list-group-item-text">@order.Description</p>
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                                    <span class="sr-only">40% Complete (success)</span>
                                                </div>
                                            </div>
                                        </a>
                                    }
                                }
                              
                            </div>
                        </div>
                        <div class="panel-footer">
                            <a class="pull-right btn btn-primary" href="#">See all</a> <br />
                            <span class="clearfix"></span>
                        </div>
                    </div>
                    </div>
                <div class="col-md-4">
                    <div id="inventoryWidget">
                        @await Component.InvokeAsync("InventoryWIdget")    
                    </div>
                    <div id="surveyWidget">
                        @await Component.InvokeAsync("SurveyWidget")
                    </div>
                    @Html.Partial("_IdeaWidget")
                </div>
                </div>
            </div>
			<!-- End View Wrapper -->

Razor/Views/Order/NewOrder.cshtml
@model  Razor.Models.Order
@inject Razor.Services.IFormDataService FormDateHelper

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Place a New Order<br />
                <small>It's what keeps us in business!</small>
            </h1>
        </div>
    </div>
    <form id="full-page-form" asp-action="NewOrder" asp-controller="Order" method="post">
        <div class="row">
            <div class="col-md-6">
                <div asp-validation-summary="All" />
                <div class="row form-group">
                    <label class="col-xs-12"  asp-for="ClientId">Client Id</label>
                    <div class="col-xs-9"><input asp-for="ClientId" type="text" class="form-control" /></div>
                    <div class="col-xs-3"><button class="btn btn-default">Lookup</button></div>
                </div>
                <div class="form-group">
                    <label asp-for="CompanyName">Company Name</label>
                    <input type="text" asp-for="CompanyName" class="form-control" />
                    <span asp-validation-for="CompanyName"/>
                </div>
                <div class="form-group">
                    <label asp-for="OrderDate">Order Date</label>
                    <input type="text" class="form-control" asp-for="OrderDate" />
                </div>
                <div class="form-group">
                    <label asp-for="Stage">Stage</label>
                    <select asp-for="Stage" class="form-control"  asp-items="FormDateHelper.GetOrderStages()"/>
                     
                </div>
                <div class="product-list">
                    @for (int i = 0; i < Model.Products.Count; i++)
                    {
                        <div class="row">
                            <input type="hidden" asp-for="@Model.Products[i].Id"/>
                            <div class="col-xs-6"><label>@Model.Products[i].Name</label></div>
                            <div class="col-xs-6"><input asp-for="@Model.Products[i].Quantity" placeholder="Quantity" type="text" class="form-control"></div>
                        </div>
                    }
                </div>
                <div class="form-group">
                    <label asp-for="ShippingAddress">Shpping Address</label>
                    <select asp-for="ShippingAddress" class="form-control">
                        <option>Mailing Address</option>
                        <option>Billing Address</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="OrderInstructions">Special Order Instructions</label>
                    <textarea asp-for="OrderInstructions" type="text" class="form-control" rows="5"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="Notes">Additional Notes</label>
                    <textarea asp-for="Notes" type="text" class="form-control" rows="5"></textarea>
                </div>
                <input type="submit" class="btn btn-primary pull-right">
            </div>
        </div>
    </form>
</div>

Razor/Views/Shared/Components/InventoryWidget/Default.cshtml
@model List<Razor.Components.InventoryItem>
<div class="panel panel-danger widget">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-tasks fa-3x"></i>
            </div>
            <div class="col-xs-9 text-right">
                <h3>Low Inventory Items</h3>
            </div>
        </div>
    </div>
    <div class="widget-display">
        <table class="table table-fluid table-striped">
            <thead>
            <tr>
                <th>Product</th>
                <th>Inventory Count</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td><a href="#" class="vote-up" data-userid="3">@item.Count</a></td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

Razor/Views/Shared/Components/SurveyWidget/Default.cshtml
@model List<Razor.Components.SurveyProduct>

<div class="panel panel-primary widget">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-3x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <h3>Coolest Product</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="widget-display">
                                <table class="table table-fluid table-striped">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Add Vote</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var product in Model)
                                        {
                                            <tr>
                                                <td>@product.Name</td>
                                                <td><a href="#" class="vote-up" data-productid="@product.Id">Vote Up</a></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>

Razor/Views/Shared/Components/SurveyWidget/Results.cshtml
@model List<Razor.Components.SurveyProduct>

<div class="panel panel-primary widget">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-3x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <h3>Coolest Product</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="widget-display">
                                <table class="table table-fluid table-striped">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Add Vote</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var product in Model)
                                        {
                                            <tr>
                                                <td>@product.Name</td>
                                                <td>@product.VoteCount</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>

Razor/Views/Shared/_IdeaWidget.cshtml
<div class="panel panel-green widget">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-tasks fa-3x"></i>
            </div>
            <div class="col-xs-9 text-right">
                <h3>Idea Center</h3>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12 feature-request">
                <p>Have an idea for new marketing materials or methods? Don't keep it to yourself!</p>
                <form action="/Home/FeatureRequest" method="post">
                                            
                    <input type="text" class="form-control" placeholder="Subject "/> <br />
                    <textarea class="form-control" id="suggestion" rows="5" type="text" placeholder="Description" name="suggestion"></textarea><br />
                    <input type="submit" value="Submit" class="improvement btn btn-primary pull-right" />
                </form>
            </div>
        </div>
    </div>
</div>

Razor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cypher Marketing</title>
    <environment names="development">
        <link asp-href-include="~/css/*.css"  rel="stylesheet" />
    </environment>
</head>
<body>
<div id="wrapper">
    @Html.Partial("_Navigation")
    @RenderBody()
</div>
<footer>
    @if (IsSectionDefined("Footer"))
    {
        RenderSection("Footer", false);
    }
    else
    {
        <p>&copy; 2016 Cypher Marketing<span class="pull-right">Contact Help Desk at 555-555-1342</span></p>
    }
</footer>
<environment names="development">
     <script asp-src-include="~/js/*.js"></script> 
     <script>
     $(document).ready(function ()  {
         $('.vote-up').click(function (e) {
             e.preventDefault();
             var id = $(this).data('productid');
             $.post('/home/vote', { id: id}, function (data) {
                 $('#surveyWidget').html(data);
             })
         })
     })
     </script>
</environment>
</body>
</html>

Razor/Views/Shared/_Navigation.cshtml
0<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"  href="/">Cypher Marketing</a>
    </div>
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <br />
            <ul class="nav" id="side-menu">
                <li>
                    <span><i class="fa fa-edit fa-fw"></i> Clients</span>
                    <ul class="nav nav-second-level in">
                        <li>
                            @Html.ActionLink("New Client","NewClient","Client")
                        </li>
                        <li>
                            <a href="#">All Clients</a>
                        </li>
                    </ul>
                </li>
                <li>
                        
                    <span><i class="fa fa-edit fa-fw"></i> Orders</span>
                    <ul class="nav nav-second-level in">
                        <li>
                            <a asp-controller="Order" asp-action="NewOrder">New Order</a>
                        </li>
                        <li>
                            <a href="#">In Progress Orders</a>
                        </li>

                        <li>
                            <a href="#">Order History</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <span><i class="fa fa-edit fa-fw"></i> Inventory</span>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#">New Item</a>
                        </li>
                        <li>
                            <a href="#">Current Inventory</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>